// Browser QA on synthetic history; no native Git operations.
import assert from 'node:assert/strict';
import { createServer } from 'vite';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const server = await createServer({ server: { host: '127.0.0.1', port: 5194, strictPort: false }, logLevel: 'error' });
await server.listen();
const browser = await chromium.launch({ headless: true, ...(process.env.CHROMIUM_EXECUTABLE_PATH ? { executablePath: process.env.CHROMIUM_EXECUTABLE_PATH } : {}) });
const errors = [];
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce' });
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(server.resolvedUrls.local[0]);
  await page.getByRole('listbox', { name: 'Commit history' }).waitFor();
  assert.equal(await page.locator('.titlebar [aria-label="Search commands"]').count(), 0);
  await page.locator('.statusbar').getByRole('button', { name: 'Search commands' }).click();
  await page.getByRole('combobox', { name: 'Search commands' }).waitFor();
  await page.keyboard.press('Escape');
  const search = page.getByRole('textbox', { name: 'Search full history' });
  await search.fill('');
  await search.fill('e');
  const rows = page.locator('.search-result-select');
  await rows.first().waitFor();
  assert.ok(await rows.count() > 20);
  assert.equal(await page.getByRole('listbox', { name: 'Commit history' }).isVisible(), false);
  const resultList = page.locator('.search-result-list');
  assert.ok(await resultList.evaluate(el => el.scrollHeight > el.clientHeight));
  await rows.first().focus();
  await page.keyboard.press('ArrowDown');
  assert.equal(await rows.nth(1).evaluate(el => el === document.activeElement), true);
  await page.keyboard.press('Enter');
  assert.equal(await rows.nth(1).getAttribute('aria-pressed'), 'true');
  assert.ok(await page.locator('.native-inspector').isVisible());
  for (const theme of ['gitty-light', 'gitty-dark']) {
    await page.getByRole('button', { name: 'Open settings', exact: true }).click();
    await page.getByRole('combobox', { name: 'Theme', exact: true }).selectOption(theme);
    await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
    await page.evaluate(() => document.fonts.ready);
    assert.ok(await resultList.evaluate(el => el.clientHeight > 300));
    if (process.env.SCREENSHOT_DIR) await page.screenshot({ path: `${process.env.SCREENSHOT_DIR}/gitty-search-${theme}.png` });
  }
  await resultList.evaluate(el => { el.scrollTop = 700; });
  await page.getByRole('button', { name: 'New tab', exact: true }).click();
  await page.locator('.tab-pane-host:not([hidden]) .statusbar').getByRole('button', { name: 'Search commands' }).click();
  await page.getByRole('combobox', { name: 'Search commands' }).waitFor();
  await page.keyboard.press('Escape');
  await page.getByRole('tab', { name: /gitty.*main/ }).click();
  await resultList.waitFor();
  assert.equal(await search.inputValue(), 'e');
  assert.ok(await resultList.evaluate(el => el.scrollTop > 600));
  await page.getByRole('button', { name: 'Graph', exact: true }).click();
  await page.getByRole('listbox', { name: 'Commit history' }).waitFor();
  await page.getByRole('button', { name: 'Results', exact: true }).click();
  assert.ok(await resultList.evaluate(el => el.scrollTop > 600));
  await resultList.evaluate(el => { el.scrollTop = 0; });
  await page.locator('.search-result-reveal').first().click();
  await page.getByRole('listbox', { name: 'Commit history' }).waitFor();
  assert.equal(await search.inputValue(), 'e');
  await search.fill('no-such-commit-search-fixture');
  await page.getByText('No matching commits', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Clear filters', exact: true }).last().click();
  await page.getByRole('listbox', { name: 'Commit history' }).waitFor();
  await search.fill('e');
  await rows.first().waitFor();
  await page.setViewportSize({ width: 600, height: 844 });
  await page.getByRole('button', { name: 'Toggle references sidebar' }).click();
  await page.getByRole('button', { name: 'Toggle working changes and inspector' }).click();
  assert.ok(await resultList.evaluate(el => el.clientWidth > 200));
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false);
  if (process.env.SCREENSHOT_DIR) await page.screenshot({ path: `${process.env.SCREENSHOT_DIR}/gitty-search-narrow.png` });
  assert.deepEqual(errors, []);
  console.log('Search browser smoke passed: full-height results, keyboard selection, graph reveal, themes, narrow layout, footer commands.');
} finally { await browser.close(); await server.close(); }
